# Generated by Django 3.2.4 on 2021-07-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrofarmacia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='clave',
            field=models.CharField(default='', max_length=20, verbose_name='clave del producto'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='descripcion',
            field=models.TextField(default='', verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='nombre',
            field=models.TextField(default='', max_length=50, verbose_name='nombre del producto'),
        ),
    ]
