# Generated by Django 3.2.4 on 2021-08-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrofarmacia', '0003_alter_medicamentos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='imagen del medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='cantidad',
            field=models.IntegerField(verbose_name='cantidad del medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='clave',
            field=models.CharField(default='', max_length=20, verbose_name='clave del medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='nombre',
            field=models.CharField(default='', max_length=50, verbose_name='nombre del medicamento'),
        ),
    ]
