# Generated by Django 3.2.4 on 2021-08-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrofarmacia', '0006_salida_medicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida_medicamento',
            name='nombre_paciente',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre del paciente'),
        ),
    ]
